name: occPy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cython
  - numpy
  - numba
  - pandas
  - scipy
  - zarr
  - boost
  - matplotlib
  - gdal
  - tqdm
  - ipykernel
  - pip:
      - seaborn
      - rasterio
      - laspy[laszip]
      - OSToolBox
      - opencv-python
variables:
  # RIVLIB_ROOT: /home/wcherlet/libs/rivlib-2_8_0-x86_64-linux-gcc9/ #ADAPT: path to rivlib here
  # RDBLIB_ROOT: /home/wcherlet/libs/rdblib-2.4.5-x86_64-linux/ #ADAPT: path to rdblib here
  PYLIDAR_CXX_FLAGS: -std=c++11 