name: occpy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cython
  - numpy
  - pandas
  - scipy
  - boost
  - matplotlib
  - tqdm
  - pip:
      - seaborn
      - rasterio
      - laspy[laszip]
      - OSToolBox
      - opencv-python
      - mkdocs
      - mkdocstrings-python
      - mkdocs-material
      - mkdocs-jupyter
      - open3d
      - pyvista
      - ipykernel
variables:
  OCCPY_CXX_FLAGS: -std=c++11 
  # RIVLIB_ROOT: #ADAPT: path to rivlib here
  # RDBLIB_ROOT: #ADAPT: path to rdblib here