site_name: OccPy
repo_url: https://github.com/dkueken/OccPy
site_dir: site
docs_dir: docs

theme:
  logo: assets/occpy_logo_v3_white.png     # light mode logo
  favicon: assets/occpy_logo_v3_white.png
  name: material
  custom_dir: docs/overrides
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: wslLight
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
    - search.suggest
use_directory_urls: false
extra_css:
  #- customs.css
  - extra.css
  - style.css
plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true
      ignore_h1_titles: True
      execute: False
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature: true
            show_source: true
            show_root_full_path: false
            separate_signature: true

markdown_extensions:
  - admonition
  - md_in_html
  - attr_list
  - abbr

nav:
  - Home: index.md
  - GitHub repository ↗: https://github.com/dkueken/OccPy
  - Notebook examples:
    - TLS: notebooks/TLS_notebook.ipynb
    - TLS_indivLAZ: notebooks/TLS_notebook_individualLAZ.ipynb
    - MLS: notebooks/MLS_notebook.ipynb
    - ULS: notebooks/ULS_notebook.ipynb
    - PyVista visualization: notebooks/pyvista.ipynb
    - PyVista interactive visualization: notebooks/pyvista_interactive.ipynb
  - Reference:
    - OccPy: ref_occpy.md
    - OccPy_Riegl: ref_occpy_riegl.md
    - util: ref_util.md
    - TerrainModel: ref_terrain_model.md
    - Visualization: ref_visualization.md
    - OccPy_Riegl_IO: ref_occpy_riegl_io.md